# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.lichuanzhi.com
date_format: "ordinal"
title: 传智博客
subtitle: "有态度的码农"
description: "李传智的个人博客"
keywords: 传智博客, ChuanZhi, Colbert
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ChuanZhi
organization: 
organization_url: 
github_username: chuanzhi
location: TianJin, China
email: chuanzhigo@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chuanzhi/chuanzhi.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: chuanzhi
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: chuanzhi
    repo: blog-comments
    oauth:
        client_id: 36f787d7e080a90b0e93
        client_secret: 8db78d03d4a5c1117f5451390ac2868cbeb190ad
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: chuanzhi
    repo: blog-comments
    clientID: 0b180ff13ae3fc97219d
    clientSecret: 479269910044e1b4b5c1f8491fa41a5843a0b265
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
